hash-format = "sha256"

[[files]]
file = "config/bcc-common.toml"
hash = "9e48e61daaee62d9b42fd7d22c21d4c9f6932fbfaee62416bede192b15e55100"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "8cf01f6d1f171b3538c911f9988f9a6e0fe3356aa50ff52f11057c7d8f7e7955"
preserve = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "ca7ccbfc12a2103e8a155731eb03f94b243cc07fe9fae2f22c9ab04656109544"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "9a9d6bf3715b20cbf83b967e4dd8b77972d1256e52a7b1c2bbfa4122f5acc931"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "547660bb17452fae6e46504c87eea9e75eeb50de440495cadcee9ad49c6d131d"
metafile = true

[[files]]
file = "mods/better-compatibility-checker.pw.toml"
hash = "7c3b1f4819e8a3b88cadd8ed968d74491c71f504738dd0f2cd60f3ff40d80f72"
metafile = true

[[files]]
file = "mods/biomespy.pw.toml"
hash = "ebcc44738754d535599c5df9e6c5118a9f3729ce30dfc7630e4c224983db26b5"
metafile = true

[[files]]
file = "mods/blocks-bogies.pw.toml"
hash = "e94f595a5a63fdabe834b84904695ccca3f9bac8856c98b57abd8687555dc213"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "91b81c2bf3b64e458a1fd5100c574244428424da770835f9f4dc3349ab18997b"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "ef7c9b68b65e7baab19dc84903f068de6714e6f306052940f53c747743d3025e"
metafile = true

[[files]]
file = "mods/bridging-mod.pw.toml"
hash = "c50696cd98b02ba03425574c7850443f5cba8e097af4b6ae1c8b42bd5316a8eb"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "c5e47d922e39c1556dc2e8c94bfe852cf16de14f65b99eb3e054e41745dddad0"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "68cc51e721e993a8b7a2cbaf45369933b22b07a9c82327ab14757ee10684aa81"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "cde21d14fcaf9495f0f5b3d8fb298dd60cb12badc21a27414c25ebf11dfb3fe1"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "5e0a875282f4abed66a2cccf7929488ebb5e88447d2bb3369e8ddc728fc66fc0"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "e002fab16a9b9ef0a35844030339612a38d3c58b0b93e97a34eb43ddc9108be7"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "7cd10de618c7f46c1877d9d3e597699a7fcc02cf3982bba439ccbec95a37d0de"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "8e671fbd3a5460a61073cced391ec08efc6b67d765e49015eea45a1f1db159a0"
metafile = true

[[files]]
file = "mods/create-bits-n-bobs.pw.toml"
hash = "eabb64a1c0e4856505110756e56df6b80d3eb2e94c0a0fdbe54a1e493fb43bea"
metafile = true

[[files]]
file = "mods/create-cardboarded-conveynience.pw.toml"
hash = "a75366f4e1b59905865a4f848ff5dc3a591b92b12483fdc8c1be10bbf5e85d09"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "dbdb686363922b46666480726b8470cbb8a6ed8386c5c3f20ff6ac06b0654e67"
metafile = true

[[files]]
file = "mods/create-design-n-decor.pw.toml"
hash = "bc4ef8bd7d32506703dcc175a62a12766addc393434ddbe8d17f01b071701943"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "ed5a88a8d97fe38cca25a42aa1ffcaf51f8f84535f872a9446eff96b92b5722a"
metafile = true

[[files]]
file = "mods/create-food.pw.toml"
hash = "c3b8a20ebb2c6f5809ade820ceb087c0be1ddfc0d99cbb4ec35074513e7cf6d2"
metafile = true

[[files]]
file = "mods/create-more-parallel-pipes.pw.toml"
hash = "fe642f391d1da67b5308987fb8ed3f4e1914d92bb181d8c05c6f5635e886b635"
metafile = true

[[files]]
file = "mods/create-pattern-schematics.pw.toml"
hash = "faddfa6807d11014c93bbfd8e543e8843e6d44e53f70d54e0b7e3e95766d2021"
metafile = true

[[files]]
file = "mods/create-railways-navigator.pw.toml"
hash = "ec69488edd55f31c6fc57cac9bab713a14394d1f63054cc4e2e5efc19a55abb9"
metafile = true

[[files]]
file = "mods/create-sound-of-steam.pw.toml"
hash = "a7a87fc6ea98d8fbaa426258990f2dec714699e98fb8a083f9a399c90d02844f"
metafile = true

[[files]]
file = "mods/create-threaded-trains.pw.toml"
hash = "cc05bcaec0e857c6a6f7de4bd09a22ad195b5b77a25e4adfe737915ac3be68db"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "9da22561c3a5e45beb91121518a49f2e8a62bedb332574ce43a9d9b287ebc705"
metafile = true

[[files]]
file = "mods/create_factory_logistics.pw.toml"
hash = "d0787f9db4af92152f43c40244becf04180b162b0d10e6263221cf18922e3f6d"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "bd005d9f92131c7c4a88a081aa5368c482eec2cb410d14ab245a2f081e9e1ffb"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "611c578745f649049988fcb24e20736589cdd7819ff9a5862b757d7a4dcc36ec"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
hash = "c7e3cfd32470d3e42baf3dc1dfcf9f17fb43df548d446ae32ec8a105d7604748"
metafile = true

[[files]]
file = "mods/easy-magic.pw.toml"
hash = "1aa75105514780685caab9b945db2a2ea7c0594ced8c01e12f2a3e331f1af4e6"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "c6d69011793e9278c65ba14423fccdbc2421f62676bad2663ba85ad9c386ae28"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9a6f001c27c05b372f72ba0941e4904ab79fb7b1a9bd5944f9d41dc79cfb8ab1"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "49b4208379d629beee2baba9b6883868a0421ea1d8d0478a4b8eff45b07be48d"
metafile = true

[[files]]
file = "mods/extra-gauges.pw.toml"
hash = "d88102f6ad27b5178453a8fdaab96a90c1174e4645d60ad312d572e31aabfed7"
metafile = true

[[files]]
file = "mods/farmers-cutting-oh-the-biomes-weve-gone.pw.toml"
hash = "5135cb75af54eb83a61156dd252d19f308b8674d0c5fd778da568527bf6031d3"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "44abae510395f12f9ea97b8296b2f72e25f18b9f3f2cc0ee42c0d9afd73fe0b3"
metafile = true

[[files]]
file = "mods/fast-leaf-decay.pw.toml"
hash = "e5c471aaab9047178ad25e91d28240fefd7b6e48d52af4274bc53239eb1da8c6"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "415ae259d7d6c92717710d6f80494d9f3c0884c6a2a35f993ad31e287f64632f"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "0004feab868f7b873c12db05aae0d0dac6c87b497490b48bb66480e7c8d0f340"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
hash = "4dcfc94168c8681f207b0124d574a970472601cd1b5e9b215a37265c753b7b47"
metafile = true

[[files]]
file = "mods/iris-flw-compat.pw.toml"
hash = "9dd90e9e80874a9f148be86a712bee40c96ea3fcb71d991f2f1f86740976d0fa"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "eb1695fedb3e6da965911e3b67914b62b1a32de6a48e2b52b38aa4d0f8d90010"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "62cd07874e73d82b29ff6fecd5345ce4b1135ce7ff29f3ef695139be33157483"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "888492de9de2384ae9b0b427624be6b004bc5882176d2c71d05d948d06cdb826"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "5367193d3f87b7bc5a81bcd64a5b96a843e76d4df7a83c8bb7e1911aa82dd52e"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7b8e8af83e8583adc91b2d859e5355f1bd0516a346d2584b8b01c004467d18af"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "3a94c8476ad2a7a2aab2d8f5ce093c3174e607aad372b509e167f587aff77cf0"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/multiplayer-server-pause.pw.toml"
hash = "5e8b5faf6de08b02b7129c80af61b59d6d7f34e1cae21a9b77d7093c77d95b85"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "abfc8909de1c851ccf4ef296e05d1017332a21fef76fd1f938828fcff925115b"
metafile = true

[[files]]
file = "mods/natures-delight.pw.toml"
hash = "e43823fe1729cb9b95311d3b8cb7f1428e230ac957c73bbf2d239921f96a229d"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "e5c9d8b97345998f99cf6da31b41c5cf4875361bc94c3354be2299730b7acb04"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "748bdcbc7788a77881979189827f1baf3f6ef5fdaeb58b00e51e043c2c0abe39"
metafile = true

[[files]]
file = "mods/oh-the-biomes-weve-gone.pw.toml"
hash = "6ad737e36e7b52b0bff6440c41e7d40e528468dad5d260481b7ec082052dbc57"
metafile = true

[[files]]
file = "mods/oh-the-trees-youll-grow.pw.toml"
hash = "bb159b7618ed1db46e01efcb27ee09c9077bb484bbe8f951575fbc220c43a2aa"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "438f930830cedabc8e10a6d008cb0a99ad9fe36bb776f426e212f60a68818fe8"
metafile = true

[[files]]
file = "mods/pretty-in-pink.pw.toml"
hash = "0617af954396c32e8a17140b6fab124cf2fd023f663956b3c4d79022f891d62f"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "c99c5bac469e8d6ece5aae80f08635e3bbb8367f0c586b6288573c725faefe69"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "6812c3faa178cd48c65c5b8e7aeef50bc0b63d8e3b2117065d6179a43d8d3649"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "198e68ce859405a409ec91f9861f3b58adf56ce3221ffb77850bef10afbf3da8"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "09248b2991edcad1048358a25ca198e15d2d7cfccd4f2bfc1d1c3b0c5b8fd6ff"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "bda23705114cea9862ea9376d169c4810b2f8fefb06381535f77e42064530a4e"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "98894c50922dfad36e4313d798d4497a61c42ce855b44fd63aea79b4990cac5d"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "49bccf856ced968a9499d110c302225b7f6d71c415d23f89db44325a72ff638a"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "743b6485780687c9736b9db5753cec0c71c761d75eb9c88a62d8a92b9a0a83bc"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "e6bb3eeda43411c95fa84549ba3281df62654e36140ec322190206fc8df512a4"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "db120825ff98ffa1a94fe66e28fd620e6ad4eae8d3ddda06b679c7d314fe49c9"
metafile = true

[[files]]
file = "mods/supplementaries-squared.pw.toml"
hash = "91ebbd7b58f32ec3cf848d203b70ef193675585d6b761de912afdd977ed5f84b"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "84a52ce6e4caafe5fb34246ff180f5c787a74faf0ff8f77e76d3e3258b96291c"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "15962183bec2468058c70e87aa32e902a08489b0f86741088cdc9aa958ba4931"
metafile = true

[[files]]
file = "mods/trimmed.pw.toml"
hash = "28db7535fae8c33b5547fefefdd88ead89c7edd7c1f330a5f370dca76e6706c9"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "473b998b1acd6c14874f9db9ae5986b1de92820456de2ff57ad4f8b2d64ccfff"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6d531ca789931cf437a72fef1a868a51d8afe4db12565a525e71c154304f4e29"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "539f362e9e192cf3b2813e0dfdfc51a5e6814129c6e82a9733842529beea6242"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "d9c0c9209bac0b693af2a7c1e47ffb28d366bad19c91df31dc6d345fa75250a1"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "31ae9ae93a8e3020278dd846c58d3376f53d2f90e2f0e8a25eab81029e2e8604"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "c2cb28859e7bcc0eb4ce59c5792f90fa5f8ab8865f5867ba26a5a345ec60b498"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "1496ffa30020676979e65921b91e583a2fdc77e50001e2ed55f99edf1a0ae880"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "03d964cba45be30fbcbef52f89f3953185737f55c8934d12e199b67194c2b368"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "c2dc09f214e7c1cecca6cf434776c2616f6d36bd27c06a6b39f985da0453a4f5"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "e839608ebc974e9e7819adc7bf29132ea86fc41b46af540fe0fa39b2007b2439"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "50c1731148d91a4ef05cfc47f759ca8fb3dad254e15ce4ecc5732d6fbfa68637"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "a2d7176026abf4a68a663b375811a603c508f36062cc7fb5b45416e1462682a8"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "03084966c05070b5c4b17cd89234f3c0d813940a2d76b405a6699deac10a0ab8"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "9854b699d5a067c46ac99b1dedeeb529bff3fc18dd079e29b438c4cbf9725f68"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "cfb7ce4c2b00cedd2e61f7d345b824d6bcc1471021668d2319ee2e4079108639"
metafile = true
