name = "AUDL Modded MC"
author = "HyloArch"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "821659bee91a2ef8a9d1fc970824796fb94551a23e3b46366307e7829487c091"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
