name = "AUDL Modded MC"
author = "HyloArch"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6ef056591230d45c6679df92f870eff084ca152f73e96b82b706ea2b5cdcb84"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
