name = "AUDL Modded MC"
author = "HyloArch"
version = "0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d69309473a9a047fb6790b6bbe844736599728b509ebe39bfa5f5dc008dfad1c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
