name = "AUDL Modded MC"
author = "HyloArch"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "795bab5067558263c40e8a5bd9d7ff4d5a61ec59d63c87b786abf395472b378c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
