name = "AUDL Modded MC"
author = "HyloArch"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aff06ffa0a3fc615c13c55313f2b3a2f1187e8f8fd61e45584a9d06fbdf0b890"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
