name = "AUDL Modded MC"
author = "HyloArch"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d642b90ebe51036cbe2753dd7e7b0bfd8f522cbed2a42e0a13b7d58dd72db1b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
